### ISSUE TITLE
Mass accept applicants

### ISSUE THREAD

**Issue by McIntireEvan** [fuseumass/dashboard#102]
Hi! 
I work with Bitcamp, and we're looking into replacing our registration system with this. One important flow we have is bulk accepting applicants given a list of emails. See [here](https://github.com/bitcamp/quill/blob/master/app/server/scripts/bulkAccept.js).

Such a feature would be excellent for us, or at the very least it'd be great to have some API documentation right out of the box so we could put together a script to do it.
Thanks for the hard work on such a great application!

**Comment by jwoglom** [comment]
Hi, thanks for considering Dashboard!

This is a perfect example of a task that we do every year, but don't have specific code in our repo which covers every use case. One script (which is a Rails rake task) you can take a look at here: https://github.com/hackumass/dashboard/blob/master/lib/tasks/admissions.rake
You should be able to trivially modify this file to filter applicants as need-be. 

Another future todo which isn't currently tracked in GitHub issues but is something that I'd like to see us add is a method of prioritizing applications; e.g., being able to set some students' application as priority level 1, some as level 2, and etc. And then when we decide on how many students we are able to accept, we can automatically pick as many as possible from group 1, flowing into group 2, until we hit our cap. 

We can use this issue for tracking more extensive automation support to the admissions rake task. Thanks for the suggestion!
