### ISSUE TITLE
Create a MVC for Judging as well as CRUD

### ISSUE THREAD

**Issue by abochnak** [fuseumass/dashboard#156]
Create a model, view, controller for live judging as well as a CRUD (create, read, update, and delete) operations in the controller.

**Comment by jonmarkgo** [comment]
How are y'all structuring the judging app? Would love to learn more about it and share any info that's helpful from what MLH has seen to make it applicable to as broad a range of events as possible

**Comment by abochnak** [comment]
Hi Jon! We currently have a design doc on this feature that we've written and will post once we are completely done with it. The idea is to make this system extensible so that no matter how a hackathon works their judging system, they will be able to use it. If you want to see an example of how we might implement this customization, take a look at how our custom event application questions work: https://github.com/fuseumass/redpandahacks-config/blob/master/event_application.yml

**Comment by ikhatri** [comment]
@jonmarkgo We've just merged our first attempt at judging into the master branch, and we have a staging instance up and running that it can be tested on. If you get in touch with us we'd love for you to take a look and give us some feedback!
