### ISSUE TITLE
Install using the docs, POST signup route missing

### ISSUE THREAD

**Issue by doftorul** [fuseumass/dashboard#169]
cloned the repo today, standard docker dev environment, after clicking the "Create new account" button:
No route matches [POST] "/signup"
Tested all the admin routes in the app, everything works as it should.

also in console:

Started POST "/signup" for XXX.XXX.XXX.XXX at 2020-01-15 20:58:17 +0000
Cannot render console from XXX.XXX.XXX.XX! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
No route matches [POST] "/signup" excluded from capture: DSN not set

ActionController::RoutingError (No route matches [POST] "/signup"):

actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.6.2) lib/web_console/middleware.rb:22:in `block in call'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
sentry-raven (2.7.4) lib/raven/integrations/rack.rb:51:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'

Does this happens because i am exposing the app on a remote server ?

Any hints ?

**Comment by jwoglom** [comment]
Looking into this, haven't been able to reproduce this locally. Is there anything else weird about your setup? (I tested on OS X docker, with the redpandahacks config repo.)

**Comment by jwoglom** [comment]
Actually, it looks like the error is in the "allowed networks" -- the Docker internal network is likely not in the range specified here. Are you maybe running in prod mode instead of dev? I would try messing with the allowed networks rails setting.

**Comment by jwoglom** [comment]
Resolved: see https://github.com/fuseumass/dashboard/commit/a5988bbbf941eac4eba31631a0e1ee5a9cac58ff
