### ISSUE TITLE
When storing resumes on Azure, if an applicant is not required to submit a resume, his "My Application Page" will show an error message

### ISSUE THREAD

**Issue by geekman7473** [fuseumass/dashboard#204]
![image](https://user-images.githubusercontent.com/2507360/73990219-82c0c100-4916-11ea-8bed-e45c462a2168.png)

**Comment by jwoglom** [comment]
Hi there, what is the URL of the Azure storage container? Check the URL of the right side iframe or hit "resume link" -- from that you should be able to configure the AZURE_STORAGE_ACCOUNT and AZURE_CONTAINER_NAME environment variables accordingly.

**Comment by jwoglom** [comment]
This should be specialcased in the template.

**Comment by AVS1508** [comment]
This issue has been migrated to #285.
