### ISSUE TITLE
Mentorship requests lack timestamp in expanded view

### ISSUE THREAD

**Issue by TG-Techie** [fuseumass/dashboard#211]
requires checking the larger list for the time stamp instead of seeing it in the expanded view.

**Comment by TG-Techie** [comment]
<img width="1352" alt="Screen Shot 2020-02-09 at 4 14 57 AM" src="https://user-images.githubusercontent.com/39284876/74099522-ca9c3f80-4af2-11ea-98a7-4045e644c972.png">
<img width="1381" alt="Screen Shot 2020-02-09 at 4 14 49 AM" src="https://user-images.githubusercontent.com/39284876/74099523-cb34d600-4af2-11ea-9cc1-47324279e35f.png">

**Comment by CodyRichter** [comment]
Issue resolved. Thanks for reporting!
