### ISSUE TITLE
Email Verification feature for Registration

### ISSUE THREAD

**Issue by shuai626** [fuseumass/dashboard#215]
Currently, a user can type in any email and password at the registration portal to create an account. There is no way to confirm that the email a user types is really their own email. This is susceptible to hacker scripts that auto-create accounts.

An email verification feature (i.e. "We've send a message to the email you provided. Please click on the attached link to verify your account and continue with the application") would be awesome!

**Comment by ikhatri** [comment]
This should be incredibly simple to implement. It's built right into device, and honestly I have no idea why we haven't had this enabled the whole time.

Please see: https://github.com/heartcombo/devise/wiki/How-To:-Add-:confirmable-to-Users

**Comment by jwoglom** [comment]
Furthermore, we have had participants who arrive on the day of the event
saying they never heard whether they got accepted or denied, and it's
because they mistyped their email! This should definitely be included in
dashboard by default.
