### ISSUE TITLE
Manual/Automatic Deploys when connected to GitHub

### ISSUE THREAD

**Issue by sahanabela** [fuseumass/dashboard#218]
Hi, we have already deployed the app but are trying to make changes and then deploy the changes. We connected Heroku to our repo (https://github.com/WEHack-UTD/redpandahacks-config), but we are getting this error when we hit the "Deploy Branch" button:

-----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/ruby.tgz
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed

We think this may be because 1) Heroku is connected to the hackathon-config folder which is what we cloned from your repo as er the instructions instead of the entire dashboard, or 2) heroku/ruby is not the correct buildpack, but I added a buildpack comatible with AWS and its still not working

How can we make sure our changes pushed to our github repo is updating our heroku app? Thanks!

**Comment by jwoglom** [comment]
Hi, we ourselves use Heroku and ran into the same problem. As far as I am aware, Heroku's automatic git deployment does not work with git submodules or the special way in which Heroku expects application static resources to be deployed.

For now, you need to deploy manually, using the deploy.sh script from a Mac or *nix machine. The deploy.sh script utilizes Docker on your machine to precompile assets inside the docker environment set up with docker_build (though, if you aren't using docker for your dev environment you can easily comment out the "./docker_shell.sh" before rails commands in that file).

Also, this shouldn't be an issue for you as your repo is already public but the hackathon config repo also has to be public as a side effect of this approach, since Heroku needs to be able to clone it (and doesn't appear to be able to utilize any ssh keys or other credentials to connect to a private repo).

We have looked into some potential remedies to this problem; one might be to allow for a Heroku environment variable to be set with the git submodule path, and upon an automatic Github deploy the application could see that if there was no hackathon-config present, then it should git clone the config repo manually. Since the deploy script also precompiles assets and pushes them to the heroku git repo, there would also need to be server side asset compilation -- something that Heroku explicitly does not recommend. Until we can figure out potential workarounds to these problems, you'll need to use the deploy script.

**Comment by sahanabela** [comment]
Ok thanks for letting us know! When I try to deploy again, I am not able to see the changes made. I can see the changes made locally through localhost:3000, but when running ./deploy.sh, the dashboard is not being updated. How can I make sure what's deployed matches what I can see locally?

**Comment by jwoglom** [comment]
Are there any errors given in the output for deploy.sh? Does Heroku say
that a deployment occurred?

**Comment by sahanabela** [comment]
It says that "HackUMass Web App Has Been Deployed" in the end but there are some errors in the output.

Running feature flag script...
 ›   Error: Multiple apps in git remotes
 ›      Usage: --remote heroku-wehack-dashboard
 ›         or: --app wehack-dashboard
 ›      Your local git repository has more than 1 app referenced in git 
 ›   remotes.
 ›      Because of this, we can't determine which app you want to run this 
 ›   command against.
 ›      Specify the app you want with --app or --remote.
 ›      Heroku remotes in repo:
 ›      wehack-dashboard (heroku)
 ›   wehack-dashboard (heroku-wehack-dashboard)
 ›
 ›      https://devcenter.heroku.com/articles/multiple-environments

To fix this I tried using this command (which was unsuccesful) --> heroku:info --app wehack-dashboard

**Comment by jwoglom** [comment]
Interesting... do you have this change applied? It may fix it:
https://github.com/fuseumass/dashboard/commit/b20003a13cbcc78091dc6f04c40119f42eafd311

If not, what is the name of your Heroku app? If you created a heroku
"pipeline" (which lets you have separate staging/production apps within one
scope), then make sure you are specifying the specific app name and not the
pipeline name when running the deploy. i.e., our pipeline name is
"dashboard" and the specific app name is "dashboard-prod" for production.

**Comment by sahanabela** [comment]
How would you apply this change (b2003a)?
The name of our Heroku app is 'wehack-dashboard'
We did not create a heroku pipeline.

**Comment by jwoglom** [comment]
Assuming you are up to date with our repo it should already be applied,
check your git history. I would try and debug where exactly the deploy
script is failing, there might just be a missing argument to some heroku
command which you need for your setup potentially.

**Comment by sahanabela** [comment]
I tried rolling back to right after I deployed for the first time on Heroku. I was hoping that since it deployed properly the first time, rolling back to that version would fix the problem. I am seeing this error when deploying and am not sure how to go about fixing it?

This is the entire output after it says 'Pushing build to Heroku':
~~~
Pushing build to Heroku....
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 564 bytes | 564.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Git submodules detected, installing:
remote: Submodule 'hackathon-config' (https://github.com/WEHack-UTD/redpandahacks-config.git) registered for path 'hackathon-config'
remote: fatal: no submodule mapping found in .gitmodules for path 'wehack-dashboard'
remote: 
remote: !	Push rejected, submodule install failed
remote: 
To https://git.heroku.com/wehack-dashboard.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/wehack-dashboard.git'
 
Heroku Build Successful ✅
 
Undoing precompile commit
Undone. Pushing to master....
remote: Permission to fuseumass/dashboard.git denied to ankitabantey.
fatal: unable to access 'https://github.com/fuseumass/dashboard.git/': The requested URL returned error: 403
Do you want to migrate the production database? (type y or n)
n
Skipping maintenance mode. No migrations found. ✅
Do you want to update the feature flag? (type y or n)
n
Skipping feature flag script ✅
HackUMass Web App Has Been Deployed ✅
~~~

Looks like this part is causing the error:
~~~
remote: fatal: no submodule mapping found in .gitmodules for path 'wehack-dashboard'
remote: 
remote: !	Push rejected, submodule install failed
remote: 
To https://git.heroku.com/wehack-dashboard.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/wehack-dashboard.git'
~~~

**Comment by jwoglom** [comment]
Okay I think the fix for this one is easy. Go to .gitmodules and
.git/config and ensure that the submodule path is set correctly. Anywhere
you see redpandahacks-config needs to be changed.

**Comment by jwoglom** [comment]
There's also an error in here about trying to push to the
fuseumass/dashboard repository, I think that's fine to ignore since you're
not on our team and don't have push access to the main repo. We should
probably fix the deploy script behavior here to not do that.

**Comment by sahanabela** [comment]
This is what is in our .gitmodules 
~~~
[submodule "hackathon-config"]
	path = hackathon-config
	url = https://github.com/WEHack-UTD/redpandahacks-config.git
~~~

But the url we have is the url of our github repo, so why should we change that? And what would we change it to?

**Comment by jwoglom** [comment]
Can you check ".git/config" inside your checked out version of dashboard?

**Comment by sahanabela** [comment]
This is what's in .git/config
~~~
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "heroku"]
	url = https://git.heroku.com/wehack-dashboard.git
	fetch = +refs/heads/*:refs/remotes/heroku/*
[branch "master"]
	remote = heroku
	merge = refs/heads/master
~~~

**Comment by jwoglom** [comment]
You most likely need to append this to .git/config:
```
[submodule "hackathon-config"]
	url = git@github.com:WEHack-UTD/redpandahacks-config.git
```
This typically happens automatically but seems to be necessary for Heroku to understand where to clone the submodule from. If you don't use ssh keys switch the `git@github.com:` for `https://github.com/`to clone via https instead of ssh.

**Comment by sahanabela** [comment]
I appended that to .git/config, it does not seem to be making a difference, unfortunately. The error I am getting still says
~~~
remote: Submodule 'hackathon-config' (https://github.com/WEHack-UTD/redpandahacks-config.git) registered for path 'hackathon-config'
remote: fatal: no submodule mapping found in .gitmodules for path 'wehack-dashboard'
remote: 
remote: !	Push rejected, submodule install failed
remote: 
To https://git.heroku.com/wehack-dashboard.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/wehack-dashboard.git'
 
Heroku Build Successful ✅
~~~

I tried changing the submodule to say "wehack-dashboard" as well even though that is not right, but it still does not work. It does specify the submodule in .gitmodules though so I am not sure what the error is really saying. Just to make sure, we just have to make these changes locally and then deploy from the Heroku CLI right?

**Comment by jwoglom** [comment]
You need to make the changes to .gitmodules and .git/config and then run
./deploy.sh. The .gitmodules file might then show up as an untracked
change, don't commit it but don't undo the changes either, the deploy
script takes care of that. I made some slight fixes to the script just now
so be sure to pull before you try again.

Do you have a folder called "wehack-dashboard" inside your dashboard
folder, by chance? The error message seems to be implying that Heroku sees
another git repo inside the current folder, which should only be happening
for the submodule. The config submodule needs to be in a folder named
"hackathon-config" and if there are any other submodules or cloned git
repos inside the dashboard folder then Heroku will panic.

**Comment by sahanabela** [comment]
Ok thank you, I will try doing that. Yes there is a folder called wehack-dashboard inside the dashboard folder, I'll try deleting that folder as well.

**Comment by ikhatri** [comment]
Closed due to inactivity. Please create a new issue if you encounter new problems.
