### ISSUE TITLE
Page 5 on dashboard

### ISSUE THREAD

**Issue by vjawahar** [fuseumass/dashboard#284]
Page 5 of the dashboard registrations crashes but all other pages are fine

**Comment by AVS1508** [comment]
The Heroku logs display:
<img width="1172" alt="Event Application - Page 5 Error" src="https://user-images.githubusercontent.com/20084950/197887722-6a6f6fec-dfbe-4319-ac89-eaad7d31dd8b.png">

**Comment by AVS1508** [comment]
A user account with a valid event application was disabled but the event application still exists, causing this display error. An email has been sent to the appropriate person to resolve the issue by Thursday, 11:59 PM.
