### ISSUE TITLE
Fix display when applicant doesn't have a resume

### ISSUE THREAD

**Issue by vjawahar** [fuseumass/dashboard#285]
- Not a priority
- Current issue when user doesn't upload a resume: 
<img width="474" alt="image" src="https://user-images.githubusercontent.com/54553038/197887152-beb2c4aa-d56a-44e9-95fe-b67cc3df7cb5.png">

**Comment by AVS1508** [comment]
Example on another device:
![image](https://user-images.githubusercontent.com/20084950/198088870-d41af845-ab38-4e39-9c85-d66b6af0fb2c.png)
