### ISSUE TITLE
NoMethodError in EventApplications

### ISSUE THREAD

**Issue by drunkbatya** [fuseumass/dashboard#300]
Hi! I'm trying to setup new clear instance, but some links fail with `NoMethodError` exception.

**Steps to reproduce:**

1. Clone main repo `git clone git@github.com:fuseumass/dashboard.git`
2. Build and run `docker compose up -d`
3. Login with default credentials, and click to `Total Registrations`(http://127.0.01:3000/event_applications) or on some user( http://127.0.01:3000/event_applications/1).
4. See the `NoMethodError in EventApplications#index` exception.

But everything works fine if query parameter `rsvp=true` is passed, like `http://127.0.01:3000/event_applications?rsvp=true`.

**Comment by drunkbatya** [comment]
Exception details:

```
Showing /usr/src/app/app/views/event_applications/index.html.erb where line #181 raised:

undefined method `rsvp' for nil:NilClass
</span>
<% end %>
<% if form.user.rsvp %>
<span class="tag tag-success event-application-header-status-margin">
RSVP
</span>
```

**Comment by ntdkhiem** [comment]
The issue is due to phantom user being accessed in `event_applications` table. Deleting that user solves the issue.
