### ISSUE TITLE
School and Majors Matching

### ISSUE THREAD

**Issue by vjawahar** [fuseumass/dashboard#301]
- No suggestions for university and majors inputs
- Issue: 
<img width="283" alt="image" src="https://user-images.githubusercontent.com/54553038/206242962-5bb9603d-d38e-4d50-b515-a974ae721a73.png">

**Comment by ntdkhiem** [comment]
I'm thinking about using [Chosen](https://harvesthq.github.io/chosen/) to display [a list of all universities in New England](https://gist.github.com/dotJoel/90c6acd65331c406d3cb). If a user can't find their school's name, I can add an extra option 'Other' and an extra text field to enter it.

**Comment by CodyRichter** [comment]
In past years, we've used the data from [these two CSV files](https://drive.google.com/drive/folders/1KxAKW2UvGBroTGOmzVkbMCUUE7hngg_6?usp=share_link) to populate the majors and universities SQL tables. You should be able to use the Heroku CLI, connect to the psql database, and then load the CSV files from your local to the tables. Feel free to do what you want with this info, but it should save you some time and get things up and running until you decide to go in another direction :)

**Comment by ntdkhiem** [comment]
Sounds good. I'll definitely check that route first 👍

**Comment by ntdkhiem** [comment]
> In past years, we've used the data from [these two CSV files](https://drive.google.com/drive/folders/1KxAKW2UvGBroTGOmzVkbMCUUE7hngg_6?usp=share_link) to populate the majors and universities SQL tables. You should be able to use the Heroku CLI, connect to the psql database, and then load the CSV files from your local to the tables. Feel free to do what you want with this info, but it should save you some time and get things up and running until you decide to go in another direction :)

I'm able to load the CSV files to the tables. Thank you!
