### ISSUE TITLE
Duplicate will in FAQ's

### ISSUE THREAD

**Issue by Akash3121** [fuseumass/dashboard#307]
There is an extra "will" in the Where is it? section in FAQ's, page link: https://hackumass.com/
![image](https://github.com/fuseumass/dashboard/assets/87650180/107224d1-368f-4167-a9f9-74e667008ba0)

I'm not able to find the place where the code is placed, If anyone can help me find it, I really appreciate that!
Thank you!

**Comment by Akash3121** [comment]
I wanna work on this, please assign this to me!!

**Comment by ammuiyer** [comment]
moved to a issue on hackumass website
