### ISSUE TITLE
Adhere to Twillio SendGrid Email Opt-in and Opt-out requirements

### ISSUE THREAD

**Issue by ntdkhiem** [fuseumass/dashboard#325]
[Twilio SendGrid Email Opt-in and Opt-out Requirements](https://support.sendgrid.com/hc/en-us/articles/4404315959835-Twilio-SendGrid-Email-Opt-in-and-Opt-out-Requirements)
[Twilio SendGrid Email Policy](https://www.twilio.com/en-us/legal/service-country-specific-terms/email)

I think the reason why we keep getting denied by AWS SES is because we haven't followed their guidelines fully. Therefore, we shouldn't make the same mistakes again with SendGrid.

- [x] We need to add an option in HUM XI's application asking for consent to collect their email. (we only ask consent for MLH)
- [x] Check all requirements from SendGrid before open the application registration.

**Comment by ntdkhiem** [comment]
#310

**Comment by ammuiyer** [comment]
For the consent, adding the option for consent to collect their emails we can do - logistics can add it, but for " Failing to provide Sender Identification when gathering consent.
Failing to maintain Sender Identification throughout communication." it just means we need to say something like "do you consent to receive emails from team@hackumass.com that contain information regarding this event?"

**Comment by ntdkhiem** [comment]
Yes, we can have an option for that during the application process. I would also mention opting-out whenever (e.g "Do you consent to receive emails from team@hackumass.com that contain information regarding this event? You will be able to opt-out at anytime through settings")

**Comment by ntdkhiem** [comment]
- [ ] add an option to opt out of notifications from HUM in non-transactional emails.
